export const Icons = {
  home: '🏠',
  profile: '👤',
  calendar: '📅',
  explore: '🔍',
  star: '⭐',
  location: '📍',
  settings: '⚙️',
  arrow: '→',
  check: '✓',
  card: '💳',
  notification: '🔔',
  beach: '🏖️',
  yoga: '🧘',
  food: '🍴',
  island: '🏝️',
  shopping: '🛍️',
  nature: '🌳',
};